#include "stm32g474xx.h"


void EXTI15_10_IRQHandler() {
	if(EXTI->PR1 & EXTI_PR1_PIF12) {
		if((GPIOB -> IDR & GPIO_IDR_ID12) == 0) {
			GPIOD -> ODR |= GPIO_ODR_OD0;
		} else if (GPIOB -> IDR & GPIO_IDR_ID12) {
			GPIOD -> ODR &= ~GPIO_ODR_OD0;
		}
		EXTI->PR1 |= EXTI_PR1_PIF12;
	}

	if(EXTI->PR1 & EXTI_PR1_PIF13) {
		if((GPIOB -> IDR & GPIO_IDR_ID13) == 0) {
			GPIOD -> ODR |= GPIO_ODR_OD1;
		} else if (GPIOB -> IDR & GPIO_IDR_ID13) {
			GPIOD -> ODR &= ~GPIO_ODR_OD1;
		}
		EXTI->PR1 |= EXTI_PR1_PIF13;
	}

	if(EXTI->PR1 & EXTI_PR1_PIF14) {
		if((GPIOB -> IDR & GPIO_IDR_ID14) == 0) {
			GPIOD -> ODR |= GPIO_ODR_OD2;
		} else if (GPIOB -> IDR & GPIO_IDR_ID14) {
			GPIOD -> ODR &= ~GPIO_ODR_OD2;
		}
		EXTI->PR1 |= EXTI_PR1_PIF14;
	}

	if(EXTI->PR1 & EXTI_PR1_PIF15) {
		if((GPIOB -> IDR & GPIO_IDR_ID15) == 0) {
			GPIOD -> ODR |= GPIO_ODR_OD3;
		} else if (GPIOB -> IDR & GPIO_IDR_ID15) {
			GPIOD -> ODR &= ~GPIO_ODR_OD3;
		}
		EXTI->PR1 |= EXTI_PR1_PIF15;
	}
}

int main(void) {
	RCC -> AHB2ENR |= RCC_AHB2ENR_GPIOBEN | RCC_AHB2ENR_GPIODEN;
	RCC -> APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	SYSCFG -> EXTICR[3] |= SYSCFG_EXTICR4_EXTI12_PB |
			SYSCFG_EXTICR4_EXTI13_PB |
			SYSCFG_EXTICR4_EXTI14_PB |
			SYSCFG_EXTICR4_EXTI15_PB;

	EXTI -> IMR1 |= EXTI_IMR1_IM12 |
			EXTI_IMR1_IM13 |
			EXTI_IMR1_IM14 |
			EXTI_IMR1_IM15;

	EXTI -> RTSR1 |= EXTI_RTSR1_RT12 |
			EXTI_RTSR1_RT13 |
			EXTI_RTSR1_RT14 |
			EXTI_RTSR1_RT15;

	EXTI -> FTSR1 |= EXTI_FTSR1_FT12 |
			EXTI_FTSR1_FT13 |
			EXTI_FTSR1_FT14 |
			EXTI_FTSR1_FT15;

	NVIC_EnableIRQ(EXTI15_10_IRQn);

	GPIOD -> MODER &= ~GPIO_MODER_MODE0_Msk &
			~GPIO_MODER_MODE1_Msk &
			~GPIO_MODER_MODE2_Msk &
			~GPIO_MODER_MODE3_Msk;

	GPIOD -> MODER |= 1 << GPIO_MODER_MODE0_Pos |
			1 << GPIO_MODER_MODE1_Pos |
			1 << GPIO_MODER_MODE2_Pos |
			1 << GPIO_MODER_MODE3_Pos;

	GPIOB -> MODER &= ~GPIO_MODER_MODE12_Msk &
			~GPIO_MODER_MODE13_Msk &
			~GPIO_MODER_MODE14_Msk &
			~GPIO_MODER_MODE15_Msk;

	GPIOB -> MODER |= 0 << GPIO_MODER_MODE12_Pos |
			0 << GPIO_MODER_MODE13_Pos |
			0 << GPIO_MODER_MODE14_Pos |
			0 << GPIO_MODER_MODE15_Pos;

	while(1) {

	}
}
